/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persamaan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author adityapeen
 */
public class Interface extends javax.swing.JFrame {
    String persamaan;
    String[][] Equ;
    int jpop;
    int jgen;
    double pc;
    double pm;
    double[][] prob;
    Chromosome[] generasi;
    int best;
    int iterasi = 0;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
        UpdateRatio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txPersamaan = new javax.swing.JTextField();
        SliderCross = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SliderMutasi = new javax.swing.JSlider();
        txPopulasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LabelCross = new javax.swing.JLabel();
        LabelMutasi = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TextGenerasi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Persamaan");
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("PERSAMAAN");

        txPersamaan.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txPersamaan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPersamaan.setText("1a+2b+3c+4d=30");

        SliderCross.setValue(25);
        SliderCross.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderCrossStateChanged(evt);
            }
        });

        jLabel2.setText("Probabilitas Crossover");

        jLabel3.setText("Probabilitas Mutasi");

        SliderMutasi.setValue(10);
        SliderMutasi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderMutasiStateChanged(evt);
            }
        });

        txPopulasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPopulasi.setText("6");

        jLabel6.setText("Populasi");

        LabelCross.setText("0.5");

        LabelMutasi.setText("0.5");

        buttonStart.setBackground(new java.awt.Color(51, 255, 51));
        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonStop.setBackground(new java.awt.Color(255, 51, 51));
        buttonStop.setText("Stop");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        jLabel7.setText("Generasi");

        TextGenerasi.setEditable(false);
        TextGenerasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextGenerasi.setText("0");
        TextGenerasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextGenerasiActionPerformed(evt);
            }
        });

        jLabel8.setText("SOLUSI");

        TextResult.setEditable(false);
        TextResult.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TextResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(LabelCross)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelMutasi)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(TextGenerasi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPersamaan, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGap(46, 46, 46))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SliderCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SliderMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txPopulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(17, 17, 17)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPersamaan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMutasi)
                    .addComponent(LabelCross))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStart)
                    .addComponent(buttonStop))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextGenerasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SliderCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SliderMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txPopulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(181, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void tampilkan(Chromosome[] pop){
        double[] terbaik = Process.terbaik(pop);
        double[] terburuk = Process.terburuk(pop);
        for(int i=0;i<pop.length;i++){
            System.out.print(pop[i].GetAngka() +" F : "+pop[i].GetFitness());
            if(i==(int)terbaik[1]) System.out.println("\t<-- Terbaik");
            else if(i==(int)terburuk[1]) System.out.println("\t<-- Terburuk");
            else System.out.println();
        }
    }
    
    private void UpdateRatio(){
        pc = Process.format(SliderCross.getValue()*0.01f);
        pm = Process.format(SliderMutasi.getValue()*0.01f);
        persamaan = txPersamaan.getText();
        Equ = GetArray(persamaan);
        jpop = Integer.valueOf(txPopulasi.getText());
        jgen = Equ[0].length-1;
        prob= new double[jpop][jpop];
        generasi = new Chromosome[jpop];
        
        LabelCross.setText(String.valueOf(pc));
        LabelMutasi.setText(String.valueOf(pm));
    }
    public static String[][] GetArray(String equation){
        String[] array = equation.split("[+=]");
        String Eq[][] = new String[2][array.length] ;
        for(int i=0;i<Eq[1].length;i++){
            Eq[0][i] = array[i].replaceAll("[^0-9?!\\.]", "");
            Eq[1][i] = array[i].replaceAll("[^a-z^A-Z?!\\.]", "");
        }        
        return Eq;
    }
    
    Timer Evolusi = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(generasi[best].GetFitness()!=1){
                System.out.println("\n\t\tGENERASI KE-"+iterasi);
                System.out.println("======POPULASI AWAL=======");
                Process.HitungProbabilitas(generasi,prob);
                tampilkan(generasi);

                System.out.println("=========SELEKSI==========");
                Chromosome seleksi[] = new Chromosome[jpop];
                Process.Seleksi(generasi, prob, seleksi);
                tampilkan(seleksi);

                System.out.println("========CROSSOVER=========");
                Chromosome[] individu = new Chromosome[jpop];
                Chromosome[] anak;
                for(int i=0; i<jpop; i+=2){
                    anak = Process.crossOver(seleksi[i], seleksi[i+1], pc);
                    individu[i] = anak[0];
                    individu[i+1] = anak[1];
                }
                tampilkan(individu);

                System.out.println("=========MUTASI==========");
                for(int i=0; i<jpop; i++){
                    individu[i] = Process.mutasi(individu[i], pm);
                }
                tampilkan(individu);

                System.out.println("========ELITISME=========");
                generasi = Process.elitisme(generasi, individu);
                tampilkan(generasi);
                ++iterasi;
                best = (int)Process.terbaik(generasi)[1];
                StringBuilder tulisan = new StringBuilder();
               
                int[] solusi = generasi[best].GetPerAbjad();
                for(int i=0;i<Equ[0].length-1;i++){
                    tulisan.append(Equ[1][i]).append("=").append(solusi[i]).append(" ");
                }
                TextGenerasi.setText(String.valueOf(iterasi-1));
                TextResult.setText(tulisan.toString());
            }
            else {
                Evolusi.stop();
                System.out.println("Proses Selesai");
                
                System.out.println("----------------------------------------");
                System.out.print(" Persamaan >>");
                System.out.println("\t"+persamaan);
                System.out.println(" Solusi ditemukan pada Generasi ke-"+(iterasi-1));
                int[] solusi = generasi[best].GetPerAbjad();
                System.out.print(" Solusi : ");
                for(int i=0;i<Equ[0].length-1;i++){
                    System.out.print(" "+Equ[1][i]+"="+solusi[i]+" ");
                }
                System.out.println("");
                System.out.println("----------------------------------------");
                JOptionPane.showMessageDialog(null, "Proses Selesai", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    });
    
    
    private void SliderCrossStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderCrossStateChanged
        // TODO add your handling code here:
        UpdateRatio();
    }//GEN-LAST:event_SliderCrossStateChanged

    private void SliderMutasiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderMutasiStateChanged
        // TODO add your handling code here:
        UpdateRatio();
    }//GEN-LAST:event_SliderMutasiStateChanged

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        iterasi=0;
        
        
        //tampilkan(generasi);
        
        
        System.out.println("Prob. Crossover = "+pc);
        System.out.println("Prob. Mutasi  = "+pm);
        System.out.println("Populasi = "+jpop);
        System.out.println("Jumlah Gen = "+jgen);
        System.out.println("Jumlah Pop = "+generasi.length);
        
        if(Integer.valueOf(txPopulasi.getText())%2==0){
            UpdateRatio();
            Process.SetEq(Equ[0]);
            Process.BangkitkanPopulasi(generasi, jgen);
            
            Evolusi.start();
        }
        else JOptionPane.showMessageDialog(null, "Populasi Harus Genap!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        // TODO add your handling code here:
        Evolusi.stop();
    }//GEN-LAST:event_buttonStopActionPerformed

    private void TextGenerasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextGenerasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextGenerasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCross;
    private javax.swing.JLabel LabelMutasi;
    private javax.swing.JSlider SliderCross;
    private javax.swing.JSlider SliderMutasi;
    private javax.swing.JTextField TextGenerasi;
    private javax.swing.JTextField TextResult;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txPersamaan;
    private javax.swing.JTextField txPopulasi;
    // End of variables declaration//GEN-END:variables
}
